In [1]:
import numpy as np
import pandas as pd

In [2]:
dict1 = {
    "name":['harry', 'adi', 'rohan'],
    "marks":[12,100,69],
    "city":['rampur', 'mumbai', 'kolkata']
}

In [3]:
df = pd.DataFrame(dict1)

In [4]:
df

    name  marks     city
0  harry     12   rampur
1    adi    100   mumbai
2  rohan     69  kolkata

In [5]:
df.to_csv('friends.csv')

In [6]:
df.to_csv('friendsfalse.csv', index=False)

In [7]:
df.head(1)

    name  marks    city
0  harry     12  rampur

In [8]:
df.tail(2)

    name  marks     city
1    adi    100   mumbai
2  rohan     69  kolkata

In [9]:
df.describe()

            marks
count    3.000000
mean    60.333333
std     44.635561
min     12.000000
25%     40.500000
50%     69.000000
75%     84.500000
max    100.000000

In [10]:
friends = pd.read_csv('friends.csv')

In [11]:
harry

NameError: name 'harry' is not defined

In [12]:
friends

   Unnamed: 0   name  marks     city
0           0  harry     12   rampur
1           1    adi    100   mumbai
2           2  rohan     69  kolkata

In [13]:
friends.index = ['first', 'second', 'human']

In [14]:
friends

        Unnamed: 0   name  marks     city
first            0  harry     12   rampur
second           1    adi    100   mumbai
human            2  rohan     69  kolkata

In [15]:
ser = pd.Series(np.random.rand(69))

In [16]:
ser

0    <built-in method rand of numpy.random.mtrand.R...
dtype: object

In [17]:
ser

0    <built-in method rand of numpy.random.mtrand.R...
dtype: object

In [18]:
type(ser)

pandas.core.series.Series

In [19]:
newdf = pd.DataFrame(np.random.rand(69, 420), index = np.arange(69))

In [21]:
newdf

,0,1,2,3,4,5,6,7,8,9,...,410,411,412,413,414,415,416,417,418,419
0,0.381106,0.010477,0.851704,0.881573,0.054372,0.965515,0.453226,0.826876,0.388407,0.307487,...,0.809182,0.731936,0.211191,0.063716,0.472692,0.660174,0.990021,0.855805,0.430653,0.202026
1,0.108621,0.969315,0.074894,0.488841,0.666148,0.041972,0.537676,0.241890,0.485923,0.462079,...,0.650190,0.272027,0.309446,0.493345,0.372537,0.142106,0.922973,0.195448,0.473654,0.101221
2,0.420684,0.445776,0.998202,0.770053,0.427642,0.277300,0.192770,0.456851,0.054645,0.432716,...,0.691150,0.308202,0.430542,0.459058,0.383556,0.227217,0.042048,0.930741,0.375602,0.685470
3,0.009509,0.987483,0.503006,0.428521,0.460401,0.593634,0.560622,0.636077,0.182093,0.102048,...,0.708549,0.955023,0.424163,0.952112,0.011809,0.483408,0.263899,0.329115,0.274195,0.586589
4,0.840925,0.392942,0.294990,0.323052,0.517959,0.644256,0.999572,0.224719,0.593310,0.187171,...,0.017805,0.016028,0.431999,0.610825,0.441370,0.991676,0.138824,0.293415,0.317069,0.331266
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
64,0.709937,0.516844,0.395014,0.657292,0.639687,0.327465,0.148398,0.068873,0.043639,0.305904,...,0.203672,0.530393,0.741343,0.416294,0.232410,0.732635,0.700552,0.380790,0.873627,0.286715
65,0.001175,0.563806,0.273121,0.084905,0.430919,0.180560,0.622901,0.832753,0.496492,0.457721,...,0.918705,0.885142,0.877861,0.476453,0.688903,0.136161,0.610971,0.577111,0.091622,0.095720
66,0.254998,0.349127,0.250932,0.394318,0.111926,0.417467,0.291913,0.075897,0.870164,0.152477,...,0.276737,0.456948,0.406677,0.832641,0.787061,0.686446,0.940785,0.379283,0.730087,0.572128
67,0.291905,0.310538,0.614050,0.511859,0.154586,0.929229,0.493408,0.078996,0.227954,0.786432,...,0.275259,0.212156,0.358835,0.196733,0.904213,0.147923,0.409255,0.227258,0.013103,0.901717
68,0.390690,0.938771,0.282826,0.299484,0.302153,0.203243,0.018194,0.079362,0.032902,0.335275,...,0.513399,0.889017,0.636374,0.078801,0.207097,0.806969,0.244927,0.672416,0.227675,0.770097

In [22]:
type(newdf)

pandas.core.frame.DataFrame

In [23]:
newdf.describe()

,0,1,2,3,4,5,6,7,8,9,...,410,411,412,413,414,415,416,417,418,419
count,69.000000,69.000000,69.000000,69.000000,69.000000,69.000000,69.000000,69.000000,69.000000,69.000000,...,69.000000,69.000000,69.000000,69.000000,69.000000,69.000000,69.000000,69.000000,69.000000,69.000000
mean,0.485913,0.465988,0.464604,0.491960,0.485756,0.505622,0.479739,0.488555,0.507215,0.428138,...,0.482790,0.468676,0.515634,0.458741,0.474856,0.450432,0.537026,0.550825,0.492523,0.487274
std,0.308746,0.289190,0.298184,0.295702,0.293400,0.308524,0.264808,0.295830,0.289202,0.305268,...,0.308794,0.322793,0.280767,0.312165,0.293253,0.281859,0.297296,0.283519,0.314614,0.297041
min,0.001175,0.010070,0.023740,0.004207,0.004779,0.003749,0.001342,0.054489,0.014404,0.000550,...,0.014732,0.000531,0.024084,0.006970,0.004800,0.012448,0.042048,0.003550,0.013103,0.014431
25%,0.233647,0.217799,0.250288,0.265598,0.286419,0.249090,0.310514,0.241890,0.260139,0.168061,...,0.203795,0.210322,0.301291,0.180189,0.232410,0.226161,0.262562,0.379283,0.197464,0.237151
50%,0.397246,0.445776,0.405953,0.488841,0.430919,0.483152,0.468262,0.463474,0.521443,0.339981,...,0.448403,0.456948,0.525179,0.476453,0.496462,0.386112,0.474313,0.559003,0.498210,0.485915
75%,0.782069,0.681493,0.709960,0.776400,0.668804,0.792564,0.635346,0.716547,0.737688,0.699443,...,0.761297,0.778313,0.741343,0.736571,0.688903,0.686446,0.848205,0.816988,0.757625,0.712133
max,0.979809,0.987483,0.998202,0.986718,0.999037,0.988366,0.999572,0.979572,0.963889,0.993856,...,0.989924,0.987079,0.999514,0.972811,0.978837,0.991676,0.995103,0.992800,0.988925,0.997826

In [24]:
newdf.dtypes

0      float64
1      float64
2      float64
3      float64
4      float64
        ...
415    float64
416    float64
417    float64
418    float64
419    float64
Length: 420, dtype: object

In [25]:
newdf.head()

,0,1,2,3,4,5,6,7,8,9,...,410,411,412,413,414,415,416,417,418,419
0,0.381106,0.010477,0.851704,0.881573,0.054372,0.965515,0.453226,0.826876,0.388407,0.307487,...,0.809182,0.731936,0.211191,0.063716,0.472692,0.660174,0.990021,0.855805,0.430653,0.202026
1,0.108621,0.969315,0.074894,0.488841,0.666148,0.041972,0.537676,0.241890,0.485923,0.462079,...,0.650190,0.272027,0.309446,0.493345,0.372537,0.142106,0.922973,0.195448,0.473654,0.101221
2,0.420684,0.445776,0.998202,0.770053,0.427642,0.277300,0.192770,0.456851,0.054645,0.432716,...,0.691150,0.308202,0.430542,0.459058,0.383556,0.227217,0.042048,0.930741,0.375602,0.685470
3,0.009509,0.987483,0.503006,0.428521,0.460401,0.593634,0.560622,0.636077,0.182093,0.102048,...,0.708549,0.955023,0.424163,0.952112,0.011809,0.483408,0.263899,0.329115,0.274195,0.586589
4,0.840925,0.392942,0.294990,0.323052,0.517959,0.644256,0.999572,0.224719,0.593310,0.187171,...,0.017805,0.016028,0.431999,0.610825,0.441370,0.991676,0.138824,0.293415,0.317069,0.331266

In [26]:
newdf[0][0] = "ado"

In [27]:
newdf.dtypes

0       object
1      float64
2      float64
3      float64
4      float64
        ...
415    float64
416    float64
417    float64
418    float64
419    float64
Length: 420, dtype: object

In [28]:
newdf.head()

,0,1,2,3,4,5,6,7,8,9,...,410,411,412,413,414,415,416,417,418,419
0,ado,0.010477,0.851704,0.881573,0.054372,0.965515,0.453226,0.826876,0.388407,0.307487,...,0.809182,0.731936,0.211191,0.063716,0.472692,0.660174,0.990021,0.855805,0.430653,0.202026
1,0.108621,0.969315,0.074894,0.488841,0.666148,0.041972,0.537676,0.241890,0.485923,0.462079,...,0.650190,0.272027,0.309446,0.493345,0.372537,0.142106,0.922973,0.195448,0.473654,0.101221
2,0.420684,0.445776,0.998202,0.770053,0.427642,0.277300,0.192770,0.456851,0.054645,0.432716,...,0.691150,0.308202,0.430542,0.459058,0.383556,0.227217,0.042048,0.930741,0.375602,0.685470
3,0.009509,0.987483,0.503006,0.428521,0.460401,0.593634,0.560622,0.636077,0.182093,0.102048,...,0.708549,0.955023,0.424163,0.952112,0.011809,0.483408,0.263899,0.329115,0.274195,0.586589
4,0.840925,0.392942,0.294990,0.323052,0.517959,0.644256,0.999572,0.224719,0.593310,0.187171,...,0.017805,0.016028,0.431999,0.610825,0.441370,0.991676,0.138824,0.293415,0.317069,0.331266

In [29]:
newdf.index

Int64Index([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
            17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33,
            34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50,
            51, 52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67,
            68],
           dtype='int64')

In [30]:
newdf.columns

RangeIndex(start=0, stop=420, step=1)

In [31]:
newdf.to_numpy()

array([['ado', 0.010477131154153163, 0.8517041187135492, ...,
        0.8558054983774147, 0.4306528114742447, 0.20202649487692392],
       [0.10862083287556601, 0.9693152390697326, 0.07489389546971237,
        ..., 0.19544788190378548, 0.47365443076432656,
        0.10122145295132368],
       [0.4206836777013945, 0.44577558078952984, 0.9982015411530656, ...,
        0.9307412116565389, 0.37560246209049564, 0.6854697498425695],
       ...,
       [0.2549979252493626, 0.349126898207165, 0.25093155787385224, ...,
        0.37928313439253036, 0.7300865482051112, 0.5721277905025678],
       [0.2919048150070618, 0.3105383048691046, 0.6140504105628563, ...,
        0.2272579607901677, 0.013102951317069067, 0.9017167035117751],
       [0.3906897608841313, 0.9387710173730124, 0.2828259792720468, ...,
        0.67241621759608, 0.22767549958428845, 0.7700968055414006]],
      dtype=object)

In [32]:
newdf[0][0] = 0.7

In [33]:
newdf.head()

,0,1,2,3,4,5,6,7,8,9,...,410,411,412,413,414,415,416,417,418,419
0,0.7,0.010477,0.851704,0.881573,0.054372,0.965515,0.453226,0.826876,0.388407,0.307487,...,0.809182,0.731936,0.211191,0.063716,0.472692,0.660174,0.990021,0.855805,0.430653,0.202026
1,0.108621,0.969315,0.074894,0.488841,0.666148,0.041972,0.537676,0.241890,0.485923,0.462079,...,0.650190,0.272027,0.309446,0.493345,0.372537,0.142106,0.922973,0.195448,0.473654,0.101221
2,0.420684,0.445776,0.998202,0.770053,0.427642,0.277300,0.192770,0.456851,0.054645,0.432716,...,0.691150,0.308202,0.430542,0.459058,0.383556,0.227217,0.042048,0.930741,0.375602,0.685470
3,0.009509,0.987483,0.503006,0.428521,0.460401,0.593634,0.560622,0.636077,0.182093,0.102048,...,0.708549,0.955023,0.424163,0.952112,0.011809,0.483408,0.263899,0.329115,0.274195,0.586589
4,0.840925,0.392942,0.294990,0.323052,0.517959,0.644256,0.999572,0.224719,0.593310,0.187171,...,0.017805,0.016028,0.431999,0.610825,0.441370,0.991676,0.138824,0.293415,0.317069,0.331266

In [34]:
newdf.t

AttributeError: 'DataFrame' object has no attribute 't'

In [35]:
newdf.T

,0,1,2,3,4,5,6,7,8,9,...,59,60,61,62,63,64,65,66,67,68
0,0.7,0.108621,0.420684,0.009509,0.840925,0.773944,0.108172,0.772999,0.206532,0.223758,...,0.510525,0.233647,0.958563,0.123978,0.632554,0.709937,0.001175,0.254998,0.291905,0.39069
1,0.010477,0.969315,0.445776,0.987483,0.392942,0.52703,0.976738,0.656366,0.058284,0.823817,...,0.88907,0.523906,0.657762,0.49242,0.681493,0.516844,0.563806,0.349127,0.310538,0.938771
2,0.851704,0.074894,0.998202,0.503006,0.29499,0.810298,0.721357,0.031866,0.893449,0.818887,...,0.930934,0.317474,0.273505,0.205358,0.540535,0.395014,0.273121,0.250932,0.61405,0.282826
3,0.881573,0.488841,0.770053,0.428521,0.323052,0.946082,0.15932,0.30937,0.046527,0.33572,...,0.520688,0.20462,0.859951,0.763123,0.413566,0.657292,0.084905,0.394318,0.511859,0.299484
4,0.054372,0.666148,0.427642,0.460401,0.517959,0.341107,0.202497,0.391333,0.413591,0.035498,...,0.096848,0.847325,0.341015,0.984001,0.50965,0.639687,0.430919,0.111926,0.154586,0.302153
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
415,0.660174,0.142106,0.227217,0.483408,0.991676,0.591888,0.750369,0.22876,0.244914,0.830896,...,0.024982,0.728178,0.865453,0.386112,0.321887,0.732635,0.136161,0.686446,0.147923,0.806969
416,0.990021,0.922973,0.042048,0.263899,0.138824,0.116278,0.21473,0.398296,0.251592,0.302449,...,0.187078,0.379155,0.995103,0.062735,0.500115,0.700552,0.610971,0.940785,0.409255,0.244927
417,0.855805,0.195448,0.930741,0.329115,0.293415,0.9928,0.891308,0.49398,0.137335,0.548138,...,0.00355,0.613439,0.832501,0.935455,0.831173,0.38079,0.577111,0.379283,0.227258,0.672416
418,0.430653,0.473654,0.375602,0.274195,0.317069,0.746256,0.048386,0.577031,0.813125,0.163554,...,0.187588,0.854557,0.940886,0.920832,0.053564,0.873627,0.091622,0.730087,0.013103,0.227675
419,0.202026,0.101221,0.68547,0.586589,0.331266,0.989965,0.257451,0.211075,0.671133,0.871008,...,0.92239,0.271265,0.051653,0.636205,0.388638,0.286715,0.09572,0.572128,0.901717,0.770097

In [36]:
newdf

,0,1,2,3,4,5,6,7,8,9,...,410,411,412,413,414,415,416,417,418,419
0,0.7,0.010477,0.851704,0.881573,0.054372,0.965515,0.453226,0.826876,0.388407,0.307487,...,0.809182,0.731936,0.211191,0.063716,0.472692,0.660174,0.990021,0.855805,0.430653,0.202026
1,0.108621,0.969315,0.074894,0.488841,0.666148,0.041972,0.537676,0.241890,0.485923,0.462079,...,0.650190,0.272027,0.309446,0.493345,0.372537,0.142106,0.922973,0.195448,0.473654,0.101221
2,0.420684,0.445776,0.998202,0.770053,0.427642,0.277300,0.192770,0.456851,0.054645,0.432716,...,0.691150,0.308202,0.430542,0.459058,0.383556,0.227217,0.042048,0.930741,0.375602,0.685470
3,0.009509,0.987483,0.503006,0.428521,0.460401,0.593634,0.560622,0.636077,0.182093,0.102048,...,0.708549,0.955023,0.424163,0.952112,0.011809,0.483408,0.263899,0.329115,0.274195,0.586589
4,0.840925,0.392942,0.294990,0.323052,0.517959,0.644256,0.999572,0.224719,0.593310,0.187171,...,0.017805,0.016028,0.431999,0.610825,0.441370,0.991676,0.138824,0.293415,0.317069,0.331266
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
64,0.709937,0.516844,0.395014,0.657292,0.639687,0.327465,0.148398,0.068873,0.043639,0.305904,...,0.203672,0.530393,0.741343,0.416294,0.232410,0.732635,0.700552,0.380790,0.873627,0.286715
65,0.001175,0.563806,0.273121,0.084905,0.430919,0.180560,0.622901,0.832753,0.496492,0.457721,...,0.918705,0.885142,0.877861,0.476453,0.688903,0.136161,0.610971,0.577111,0.091622,0.095720
66,0.254998,0.349127,0.250932,0.394318,0.111926,0.417467,0.291913,0.075897,0.870164,0.152477,...,0.276737,0.456948,0.406677,0.832641,0.787061,0.686446,0.940785,0.379283,0.730087,0.572128
67,0.291905,0.310538,0.614050,0.511859,0.154586,0.929229,0.493408,0.078996,0.227954,0.786432,...,0.275259,0.212156,0.358835,0.196733,0.904213,0.147923,0.409255,0.227258,0.013103,0.901717
68,0.39069,0.938771,0.282826,0.299484,0.302153,0.203243,0.018194,0.079362,0.032902,0.335275,...,0.513399,0.889017,0.636374,0.078801,0.207097,0.806969,0.244927,0.672416,0.227675,0.770097

In [37]:
newdf.tail

<bound method NDFrame.tail of          0         1         2         3         4         5         6    \
0        0.7  0.010477  0.851704  0.881573  0.054372  0.965515  0.453226
1   0.108621  0.969315  0.074894  0.488841  0.666148  0.041972  0.537676
2   0.420684  0.445776  0.998202  0.770053  0.427642  0.277300  0.192770
3   0.009509  0.987483  0.503006  0.428521  0.460401  0.593634  0.560622
4   0.840925  0.392942  0.294990  0.323052  0.517959  0.644256  0.999572
..       ...       ...       ...       ...       ...       ...       ...
64  0.709937  0.516844  0.395014  0.657292  0.639687  0.327465  0.148398
65  0.001175  0.563806  0.273121  0.084905  0.430919  0.180560  0.622901
66  0.254998  0.349127  0.250932  0.394318  0.111926  0.417467  0.291913
67  0.291905  0.310538  0.614050  0.511859  0.154586  0.929229  0.493408
68   0.39069  0.938771  0.282826  0.299484  0.302153  0.203243  0.018194

         7         8         9    ...       410       411       412       413  \
0   0.826876  0.388407  0.307487  ...  0.809182  0.731936  0.211191  0.063716
1   0.241890  0.485923  0.462079  ...  0.650190  0.272027  0.309446  0.493345
2   0.456851  0.054645  0.432716  ...  0.691150  0.308202  0.430542  0.459058
3   0.636077  0.182093  0.102048  ...  0.708549  0.955023  0.424163  0.952112
4   0.224719  0.593310  0.187171  ...  0.017805  0.016028  0.431999  0.610825
..       ...       ...       ...  ...       ...       ...       ...       ...
64  0.068873  0.043639  0.305904  ...  0.203672  0.530393  0.741343  0.416294
65  0.832753  0.496492  0.457721  ...  0.918705  0.885142  0.877861  0.476453
66  0.075897  0.870164  0.152477  ...  0.276737  0.456948  0.406677  0.832641
67  0.078996  0.227954  0.786432  ...  0.275259  0.212156  0.358835  0.196733
68  0.079362  0.032902  0.335275  ...  0.513399  0.889017  0.636374  0.078801

         414       415       416       417       418       419
0   0.472692  0.660174  0.990021  0.855805  0.430653  0.202026
1   0.372537  0.142106  0.922973  0.195448  0.473654  0.101221
2   0.383556  0.227217  0.042048  0.930741  0.375602  0.685470
3   0.011809  0.483408  0.263899  0.329115  0.274195  0.586589
4   0.441370  0.991676  0.138824  0.293415  0.317069  0.331266
..       ...       ...       ...       ...       ...       ...
64  0.232410  0.732635  0.700552  0.380790  0.873627  0.286715
65  0.688903  0.136161  0.610971  0.577111  0.091622  0.095720
66  0.787061  0.686446  0.940785  0.379283  0.730087  0.572128
67  0.904213  0.147923  0.409255  0.227258  0.013103  0.901717
68  0.207097  0.806969  0.244927  0.672416  0.227675  0.770097

[69 rows x 420 columns]>

In [39]:
newdf.sort_index(axis=2, ascending = False) #axis has to be 1 or 0

ValueError: No axis named 2 for object type DataFrame

In [40]:
newdf.head()

,0,1,2,3,4,5,6,7,8,9,...,410,411,412,413,414,415,416,417,418,419
0,0.7,0.010477,0.851704,0.881573,0.054372,0.965515,0.453226,0.826876,0.388407,0.307487,...,0.809182,0.731936,0.211191,0.063716,0.472692,0.660174,0.990021,0.855805,0.430653,0.202026
1,0.108621,0.969315,0.074894,0.488841,0.666148,0.041972,0.537676,0.241890,0.485923,0.462079,...,0.650190,0.272027,0.309446,0.493345,0.372537,0.142106,0.922973,0.195448,0.473654,0.101221
2,0.420684,0.445776,0.998202,0.770053,0.427642,0.277300,0.192770,0.456851,0.054645,0.432716,...,0.691150,0.308202,0.430542,0.459058,0.383556,0.227217,0.042048,0.930741,0.375602,0.685470
3,0.009509,0.987483,0.503006,0.428521,0.460401,0.593634,0.560622,0.636077,0.182093,0.102048,...,0.708549,0.955023,0.424163,0.952112,0.011809,0.483408,0.263899,0.329115,0.274195,0.586589
4,0.840925,0.392942,0.294990,0.323052,0.517959,0.644256,0.999572,0.224719,0.593310,0.187171,...,0.017805,0.016028,0.431999,0.610825,0.441370,0.991676,0.138824,0.293415,0.317069,0.331266

In [41]:
newdf[0]

0          0.7
1     0.108621
2     0.420684
3     0.009509
4     0.840925
        ...
64    0.709937
65    0.001175
66    0.254998
67    0.291905
68     0.39069
Name: 0, Length: 69, dtype: object

In [42]:
type(newdf[0])

pandas.core.series.Series

In [43]:
newdf2 = newdf

In [44]:
newdf2

,0,1,2,3,4,5,6,7,8,9,...,410,411,412,413,414,415,416,417,418,419
0,0.7,0.010477,0.851704,0.881573,0.054372,0.965515,0.453226,0.826876,0.388407,0.307487,...,0.809182,0.731936,0.211191,0.063716,0.472692,0.660174,0.990021,0.855805,0.430653,0.202026
1,0.108621,0.969315,0.074894,0.488841,0.666148,0.041972,0.537676,0.241890,0.485923,0.462079,...,0.650190,0.272027,0.309446,0.493345,0.372537,0.142106,0.922973,0.195448,0.473654,0.101221
2,0.420684,0.445776,0.998202,0.770053,0.427642,0.277300,0.192770,0.456851,0.054645,0.432716,...,0.691150,0.308202,0.430542,0.459058,0.383556,0.227217,0.042048,0.930741,0.375602,0.685470
3,0.009509,0.987483,0.503006,0.428521,0.460401,0.593634,0.560622,0.636077,0.182093,0.102048,...,0.708549,0.955023,0.424163,0.952112,0.011809,0.483408,0.263899,0.329115,0.274195,0.586589
4,0.840925,0.392942,0.294990,0.323052,0.517959,0.644256,0.999572,0.224719,0.593310,0.187171,...,0.017805,0.016028,0.431999,0.610825,0.441370,0.991676,0.138824,0.293415,0.317069,0.331266
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
64,0.709937,0.516844,0.395014,0.657292,0.639687,0.327465,0.148398,0.068873,0.043639,0.305904,...,0.203672,0.530393,0.741343,0.416294,0.232410,0.732635,0.700552,0.380790,0.873627,0.286715
65,0.001175,0.563806,0.273121,0.084905,0.430919,0.180560,0.622901,0.832753,0.496492,0.457721,...,0.918705,0.885142,0.877861,0.476453,0.688903,0.136161,0.610971,0.577111,0.091622,0.095720
66,0.254998,0.349127,0.250932,0.394318,0.111926,0.417467,0.291913,0.075897,0.870164,0.152477,...,0.276737,0.456948,0.406677,0.832641,0.787061,0.686446,0.940785,0.379283,0.730087,0.572128
67,0.291905,0.310538,0.614050,0.511859,0.154586,0.929229,0.493408,0.078996,0.227954,0.786432,...,0.275259,0.212156,0.358835,0.196733,0.904213,0.147923,0.409255,0.227258,0.013103,0.901717
68,0.39069,0.938771,0.282826,0.299484,0.302153,0.203243,0.018194,0.079362,0.032902,0.335275,...,0.513399,0.889017,0.636374,0.078801,0.207097,0.806969,0.244927,0.672416,0.227675,0.770097

In [45]:
newdf2[0][0] = 98492

In [46]:
newdf

,0,1,2,3,4,5,6,7,8,9,...,410,411,412,413,414,415,416,417,418,419
0,98492,0.010477,0.851704,0.881573,0.054372,0.965515,0.453226,0.826876,0.388407,0.307487,...,0.809182,0.731936,0.211191,0.063716,0.472692,0.660174,0.990021,0.855805,0.430653,0.202026
1,0.108621,0.969315,0.074894,0.488841,0.666148,0.041972,0.537676,0.241890,0.485923,0.462079,...,0.650190,0.272027,0.309446,0.493345,0.372537,0.142106,0.922973,0.195448,0.473654,0.101221
2,0.420684,0.445776,0.998202,0.770053,0.427642,0.277300,0.192770,0.456851,0.054645,0.432716,...,0.691150,0.308202,0.430542,0.459058,0.383556,0.227217,0.042048,0.930741,0.375602,0.685470
3,0.009509,0.987483,0.503006,0.428521,0.460401,0.593634,0.560622,0.636077,0.182093,0.102048,...,0.708549,0.955023,0.424163,0.952112,0.011809,0.483408,0.263899,0.329115,0.274195,0.586589
4,0.840925,0.392942,0.294990,0.323052,0.517959,0.644256,0.999572,0.224719,0.593310,0.187171,...,0.017805,0.016028,0.431999,0.610825,0.441370,0.991676,0.138824,0.293415,0.317069,0.331266
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
64,0.709937,0.516844,0.395014,0.657292,0.639687,0.327465,0.148398,0.068873,0.043639,0.305904,...,0.203672,0.530393,0.741343,0.416294,0.232410,0.732635,0.700552,0.380790,0.873627,0.286715
65,0.001175,0.563806,0.273121,0.084905,0.430919,0.180560,0.622901,0.832753,0.496492,0.457721,...,0.918705,0.885142,0.877861,0.476453,0.688903,0.136161,0.610971,0.577111,0.091622,0.095720
66,0.254998,0.349127,0.250932,0.394318,0.111926,0.417467,0.291913,0.075897,0.870164,0.152477,...,0.276737,0.456948,0.406677,0.832641,0.787061,0.686446,0.940785,0.379283,0.730087,0.572128
67,0.291905,0.310538,0.614050,0.511859,0.154586,0.929229,0.493408,0.078996,0.227954,0.786432,...,0.275259,0.212156,0.358835,0.196733,0.904213,0.147923,0.409255,0.227258,0.013103,0.901717
68,0.39069,0.938771,0.282826,0.299484,0.302153,0.203243,0.018194,0.079362,0.032902,0.335275,...,0.513399,0.889017,0.636374,0.078801,0.207097,0.806969,0.244927,0.672416,0.227675,0.770097

In [47]:
newdf3 = newdf.copy()

In [48]:
newdf3[0][0] = 9283492

C:\Users\adity\AppData\Local\Temp/ipykernel_21468/2334661463.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  newdf3[0][0] = 9283492

In [49]:
newdf #newdf3 is a copy but newdf2 is a pointer to newdf

,0,1,2,3,4,5,6,7,8,9,...,410,411,412,413,414,415,416,417,418,419
0,98492,0.010477,0.851704,0.881573,0.054372,0.965515,0.453226,0.826876,0.388407,0.307487,...,0.809182,0.731936,0.211191,0.063716,0.472692,0.660174,0.990021,0.855805,0.430653,0.202026
1,0.108621,0.969315,0.074894,0.488841,0.666148,0.041972,0.537676,0.241890,0.485923,0.462079,...,0.650190,0.272027,0.309446,0.493345,0.372537,0.142106,0.922973,0.195448,0.473654,0.101221
2,0.420684,0.445776,0.998202,0.770053,0.427642,0.277300,0.192770,0.456851,0.054645,0.432716,...,0.691150,0.308202,0.430542,0.459058,0.383556,0.227217,0.042048,0.930741,0.375602,0.685470
3,0.009509,0.987483,0.503006,0.428521,0.460401,0.593634,0.560622,0.636077,0.182093,0.102048,...,0.708549,0.955023,0.424163,0.952112,0.011809,0.483408,0.263899,0.329115,0.274195,0.586589
4,0.840925,0.392942,0.294990,0.323052,0.517959,0.644256,0.999572,0.224719,0.593310,0.187171,...,0.017805,0.016028,0.431999,0.610825,0.441370,0.991676,0.138824,0.293415,0.317069,0.331266
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
64,0.709937,0.516844,0.395014,0.657292,0.639687,0.327465,0.148398,0.068873,0.043639,0.305904,...,0.203672,0.530393,0.741343,0.416294,0.232410,0.732635,0.700552,0.380790,0.873627,0.286715
65,0.001175,0.563806,0.273121,0.084905,0.430919,0.180560,0.622901,0.832753,0.496492,0.457721,...,0.918705,0.885142,0.877861,0.476453,0.688903,0.136161,0.610971,0.577111,0.091622,0.095720
66,0.254998,0.349127,0.250932,0.394318,0.111926,0.417467,0.291913,0.075897,0.870164,0.152477,...,0.276737,0.456948,0.406677,0.832641,0.787061,0.686446,0.940785,0.379283,0.730087,0.572128
67,0.291905,0.310538,0.614050,0.511859,0.154586,0.929229,0.493408,0.078996,0.227954,0.786432,...,0.275259,0.212156,0.358835,0.196733,0.904213,0.147923,0.409255,0.227258,0.013103,0.901717
68,0.39069,0.938771,0.282826,0.299484,0.302153,0.203243,0.018194,0.079362,0.032902,0.335275,...,0.513399,0.889017,0.636374,0.078801,0.207097,0.806969,0.244927,0.672416,0.227675,0.770097

In [50]:
newdf.loc[0,0] = 654

In [51]:
newdf.head()

,0,1,2,3,4,5,6,7,8,9,...,410,411,412,413,414,415,416,417,418,419
0,654,0.010477,0.851704,0.881573,0.054372,0.965515,0.453226,0.826876,0.388407,0.307487,...,0.809182,0.731936,0.211191,0.063716,0.472692,0.660174,0.990021,0.855805,0.430653,0.202026
1,0.108621,0.969315,0.074894,0.488841,0.666148,0.041972,0.537676,0.241890,0.485923,0.462079,...,0.650190,0.272027,0.309446,0.493345,0.372537,0.142106,0.922973,0.195448,0.473654,0.101221
2,0.420684,0.445776,0.998202,0.770053,0.427642,0.277300,0.192770,0.456851,0.054645,0.432716,...,0.691150,0.308202,0.430542,0.459058,0.383556,0.227217,0.042048,0.930741,0.375602,0.685470
3,0.009509,0.987483,0.503006,0.428521,0.460401,0.593634,0.560622,0.636077,0.182093,0.102048,...,0.708549,0.955023,0.424163,0.952112,0.011809,0.483408,0.263899,0.329115,0.274195,0.586589
4,0.840925,0.392942,0.294990,0.323052,0.517959,0.644256,0.999572,0.224719,0.593310,0.187171,...,0.017805,0.016028,0.431999,0.610825,0.441370,0.991676,0.138824,0.293415,0.317069,0.331266

In [52]:
newdf.columns = list("ABCDE") #I have 420 columns but I have only given 5 charachters

ValueError: Length mismatch: Expected axis has 420 elements, new values have 5 elements

In [53]:
newdf.head()

,0,1,2,3,4,5,6,7,8,9,...,410,411,412,413,414,415,416,417,418,419
0,654,0.010477,0.851704,0.881573,0.054372,0.965515,0.453226,0.826876,0.388407,0.307487,...,0.809182,0.731936,0.211191,0.063716,0.472692,0.660174,0.990021,0.855805,0.430653,0.202026
1,0.108621,0.969315,0.074894,0.488841,0.666148,0.041972,0.537676,0.241890,0.485923,0.462079,...,0.650190,0.272027,0.309446,0.493345,0.372537,0.142106,0.922973,0.195448,0.473654,0.101221
2,0.420684,0.445776,0.998202,0.770053,0.427642,0.277300,0.192770,0.456851,0.054645,0.432716,...,0.691150,0.308202,0.430542,0.459058,0.383556,0.227217,0.042048,0.930741,0.375602,0.685470
3,0.009509,0.987483,0.503006,0.428521,0.460401,0.593634,0.560622,0.636077,0.182093,0.102048,...,0.708549,0.955023,0.424163,0.952112,0.011809,0.483408,0.263899,0.329115,0.274195,0.586589
4,0.840925,0.392942,0.294990,0.323052,0.517959,0.644256,0.999572,0.224719,0.593310,0.187171,...,0.017805,0.016028,0.431999,0.610825,0.441370,0.991676,0.138824,0.293415,0.317069,0.331266

In [54]:
newdf = newdf.drop(0, axis = 1)

In [55]:
newdf.head

<bound method NDFrame.head of          1         2         3         4         5         6         7    \
0   0.010477  0.851704  0.881573  0.054372  0.965515  0.453226  0.826876
1   0.969315  0.074894  0.488841  0.666148  0.041972  0.537676  0.241890
2   0.445776  0.998202  0.770053  0.427642  0.277300  0.192770  0.456851
3   0.987483  0.503006  0.428521  0.460401  0.593634  0.560622  0.636077
4   0.392942  0.294990  0.323052  0.517959  0.644256  0.999572  0.224719
..       ...       ...       ...       ...       ...       ...       ...
64  0.516844  0.395014  0.657292  0.639687  0.327465  0.148398  0.068873
65  0.563806  0.273121  0.084905  0.430919  0.180560  0.622901  0.832753
66  0.349127  0.250932  0.394318  0.111926  0.417467  0.291913  0.075897
67  0.310538  0.614050  0.511859  0.154586  0.929229  0.493408  0.078996
68  0.938771  0.282826  0.299484  0.302153  0.203243  0.018194  0.079362

         8         9         10   ...       410       411       412       413  \
0   0.388407  0.307487  0.235739  ...  0.809182  0.731936  0.211191  0.063716
1   0.485923  0.462079  0.763676  ...  0.650190  0.272027  0.309446  0.493345
2   0.054645  0.432716  0.816556  ...  0.691150  0.308202  0.430542  0.459058
3   0.182093  0.102048  0.405561  ...  0.708549  0.955023  0.424163  0.952112
4   0.593310  0.187171  0.989244  ...  0.017805  0.016028  0.431999  0.610825
..       ...       ...       ...  ...       ...       ...       ...       ...
64  0.043639  0.305904  0.605892  ...  0.203672  0.530393  0.741343  0.416294
65  0.496492  0.457721  0.309134  ...  0.918705  0.885142  0.877861  0.476453
66  0.870164  0.152477  0.236123  ...  0.276737  0.456948  0.406677  0.832641
67  0.227954  0.786432  0.512580  ...  0.275259  0.212156  0.358835  0.196733
68  0.032902  0.335275  0.608944  ...  0.513399  0.889017  0.636374  0.078801

         414       415       416       417       418       419
0   0.472692  0.660174  0.990021  0.855805  0.430653  0.202026
1   0.372537  0.142106  0.922973  0.195448  0.473654  0.101221
2   0.383556  0.227217  0.042048  0.930741  0.375602  0.685470
3   0.011809  0.483408  0.263899  0.329115  0.274195  0.586589
4   0.441370  0.991676  0.138824  0.293415  0.317069  0.331266
..       ...       ...       ...       ...       ...       ...
64  0.232410  0.732635  0.700552  0.380790  0.873627  0.286715
65  0.688903  0.136161  0.610971  0.577111  0.091622  0.095720
66  0.787061  0.686446  0.940785  0.379283  0.730087  0.572128
67  0.904213  0.147923  0.409255  0.227258  0.013103  0.901717
68  0.207097  0.806969  0.244927  0.672416  0.227675  0.770097

[69 rows x 419 columns]>

In [56]:
newdf.head() # 1 column was removed because we ran the function newdf.drop

,1,2,3,4,5,6,7,8,9,10,...,410,411,412,413,414,415,416,417,418,419
0,0.010477,0.851704,0.881573,0.054372,0.965515,0.453226,0.826876,0.388407,0.307487,0.235739,...,0.809182,0.731936,0.211191,0.063716,0.472692,0.660174,0.990021,0.855805,0.430653,0.202026
1,0.969315,0.074894,0.488841,0.666148,0.041972,0.537676,0.241890,0.485923,0.462079,0.763676,...,0.650190,0.272027,0.309446,0.493345,0.372537,0.142106,0.922973,0.195448,0.473654,0.101221
2,0.445776,0.998202,0.770053,0.427642,0.277300,0.192770,0.456851,0.054645,0.432716,0.816556,...,0.691150,0.308202,0.430542,0.459058,0.383556,0.227217,0.042048,0.930741,0.375602,0.685470
3,0.987483,0.503006,0.428521,0.460401,0.593634,0.560622,0.636077,0.182093,0.102048,0.405561,...,0.708549,0.955023,0.424163,0.952112,0.011809,0.483408,0.263899,0.329115,0.274195,0.586589
4,0.392942,0.294990,0.323052,0.517959,0.644256,0.999572,0.224719,0.593310,0.187171,0.989244,...,0.017805,0.016028,0.431999,0.610825,0.441370,0.991676,0.138824,0.293415,0.317069,0.331266

In [57]:
newdf.loc[[1,2], ['C', 'D']]

KeyError: "None of [Index(['C', 'D'], dtype='object')] are in the [columns]"

In [58]:
newdf.drop([22,23], axis=1, inplace=True) # you can drop multiple values and inplace makes a change to the actual df

In [59]:
newdf

,1,2,3,4,5,6,7,8,9,10,...,410,411,412,413,414,415,416,417,418,419
0,0.010477,0.851704,0.881573,0.054372,0.965515,0.453226,0.826876,0.388407,0.307487,0.235739,...,0.809182,0.731936,0.211191,0.063716,0.472692,0.660174,0.990021,0.855805,0.430653,0.202026
1,0.969315,0.074894,0.488841,0.666148,0.041972,0.537676,0.241890,0.485923,0.462079,0.763676,...,0.650190,0.272027,0.309446,0.493345,0.372537,0.142106,0.922973,0.195448,0.473654,0.101221
2,0.445776,0.998202,0.770053,0.427642,0.277300,0.192770,0.456851,0.054645,0.432716,0.816556,...,0.691150,0.308202,0.430542,0.459058,0.383556,0.227217,0.042048,0.930741,0.375602,0.685470
3,0.987483,0.503006,0.428521,0.460401,0.593634,0.560622,0.636077,0.182093,0.102048,0.405561,...,0.708549,0.955023,0.424163,0.952112,0.011809,0.483408,0.263899,0.329115,0.274195,0.586589
4,0.392942,0.294990,0.323052,0.517959,0.644256,0.999572,0.224719,0.593310,0.187171,0.989244,...,0.017805,0.016028,0.431999,0.610825,0.441370,0.991676,0.138824,0.293415,0.317069,0.331266
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
64,0.516844,0.395014,0.657292,0.639687,0.327465,0.148398,0.068873,0.043639,0.305904,0.605892,...,0.203672,0.530393,0.741343,0.416294,0.232410,0.732635,0.700552,0.380790,0.873627,0.286715
65,0.563806,0.273121,0.084905,0.430919,0.180560,0.622901,0.832753,0.496492,0.457721,0.309134,...,0.918705,0.885142,0.877861,0.476453,0.688903,0.136161,0.610971,0.577111,0.091622,0.095720
66,0.349127,0.250932,0.394318,0.111926,0.417467,0.291913,0.075897,0.870164,0.152477,0.236123,...,0.276737,0.456948,0.406677,0.832641,0.787061,0.686446,0.940785,0.379283,0.730087,0.572128
67,0.310538,0.614050,0.511859,0.154586,0.929229,0.493408,0.078996,0.227954,0.786432,0.512580,...,0.275259,0.212156,0.358835,0.196733,0.904213,0.147923,0.409255,0.227258,0.013103,0.901717
68,0.938771,0.282826,0.299484,0.302153,0.203243,0.018194,0.079362,0.032902,0.335275,0.608944,...,0.513399,0.889017,0.636374,0.078801,0.207097,0.806969,0.244927,0.672416,0.227675,0.770097

In [60]:
df = pd.DataFrame({
    "name": ['alfie', 'po']
    "toy": [np.nan, 'batgun']
    "born": [pd.Nat, pd.Timestamp("1940-04-25")]
})

SyntaxError: invalid syntax (Temp/ipykernel_21468/4152409651.py, line 3)

In [61]:
df = pd.DataFrame({
    "name": ['alfie', 'po'],
    "toy": [np.nan, 'batgun'],
    "born": [pd.Nat, pd.Timestamp("1940-04-25")]
})

AttributeError: module 'pandas' has no attribute 'Nat'